### ISSUE TITLE
UBsync 'start: job failed to start' error from the UT Log viewer app

### ISSUE THREAD

**Issue by clendee** [belohoub/UBsync#1]
Hi,

Firstly, thank you for attempting to port the UBsync app to the arm64 version of UT.

Im having an issue when I click on 'Start' to start the service.

start: Job failed to start
qml: PopupStatusBox.qml - hide
qml: PopupStatusBox.qml - hide
QObject::startTimer: Timers cannot be started from another thread.

Im using an existing connected Nextcloud account that I use for the calendar app and Jotit cloud notes.
When I select that account for UBsync, I get the above errors in the Log Viewer.

Thanks.

**Comment by belohoub** [comment]
Hello,
Unfortunately, I'm not very familiar with QML and additionaly I do did not observe this error.

I was able to find out, that the problem is that the timer object resides in the main thread, however it is called from outside.

Using [this](https://stackoverflow.com/questions/28507619/how-to-create-delay-function-in-qml) post, I was able to modify the code and hopefully, the error should disappear, but I observed no error before and I observe no error now :-D

So, you are free to test this package: [ubsync.zip](https://github.com/belohoub/UBsync/files/6084136/ubsync.zip) or build ...

**Comment by clendee** [comment]
Hi, thanks for looking into this so promptly.

I installed the new version from the zip file above.  Im afraid Im getting the same or similar error when I try to attach my existing nextcloud account on the phone to UBsync.  This error appears when I go to 'Sync Service' and press 'Start'

Here is the output of the ubsync log file
[https://paste.ubuntu.com/p/QSy7jYNZQb/](https://paste.ubuntu.com/p/QSy7jYNZQb/)

Is this app working ok for you on arm64? and are you managing to sync folders with Nextcloud?

Hope this helps,
Thanks for your time in looking into this.

**Comment by belohoub** [comment]
Well, well :-)

As I said, I'm not familiar with QML and I currently don't have capacity to invest too much time to it.

Unfortunately, I have no idea how to solve it correctly in QML. Additionaly, I cannot reproduce the error on my device - it might be QML version-dependent (?) 

Causes the error application crashes? If it does. I can disable hiding at all - it seems to be acceptable, at it occupies only a small area in the bottom part of the display...

**Comment by clendee** [comment]
Thats ok.  I appreciate being able to at least know its operational for someone.

The issue for me is I cannot start the Sync Service at all, so I feel hiding the output wont probably solve anything Im afraid.
Thanks again for your efforts.

**Comment by belohoub** [comment]
My idea was different - not only supress the message,, but supress the function, which provides hiding (remove the function call causing the error) - this is something I can do. This removes the source of this error completely, while the message in the bottom will not disappear. If this causes your UBSync crashing, this should resolve it for you.
You can try this package: [ubsync.zip](https://github.com/belohoub/UBsync/files/6084757/ubsync.zip)

FYI, my UT version is 2021-W09

**Comment by clendee** [comment]
My version of UT is Software: OS ubuntu 16.04 (2021-03-02) - From the About page.

The sync and exclamation mark now stays active at the bottom of the screen, see image.  Whereas before it would just flash on and off.  The service will not start at all.


![screenshot20210304_155333600](https://user-images.githubusercontent.com/50013459/109991394-335be880-7d02-11eb-9856-7d1614bd0683.png)

Here is a link to the output from the Log Viewer.

[http://paste.ubuntu.com/p/fm7PwX6pDX/](http://paste.ubuntu.com/p/fm7PwX6pDX/)

**Comment by belohoub** [comment]
And what about your config file *.config/upstart/OwncloudSyncd.conf*?

Should look like this:
```
start on started unity8
pre-start script
   initctl set-env LD_LIBRARY_PATH=/opt/click.ubuntu.com/ubsync/current/lib/aarch64-linux-gnu/
end script
exec /opt/click.ubuntu.com/ubsync/current/lib/aarch64-linux-gnu/bin/OwncloudSyncd
```

**Comment by clendee** [comment]
Well done, you sorted it out.

When I replaced my .config/upstart/OwncloudSyncd.conf with the contents you provided above, UBsync started syncing my photos.

Thank you so much.

**Comment by belohoub** [comment]
well - this was probably old config from your attempts ... :-)
