### ISSUE TITLE
Problem refreshing when columns are shown (wide screens)

### ISSUE THREAD

**Issue by j2g2rp** [belohoub/UBsync#17]
This bug can be reproduced on 0.7.2 when the screen is wide enough to show columns.
When you are creating new targets the left column where targets should be shown is not refreshed (left column). There are two possibilities: 

1. If you are configuring the first targets after select an account on the left column will be showing the startup procedure guiding you to account icon. There is no possibilities to refresh this column manually just closing the app and opening again. If you had configured a target the target is shown there.
2. If you already had some targets you can refresh the targets scrolling left column.

**Comment by belohoub** [comment]
@j2g2rp could you please test the updated layout? This issue should disappear in any form, as the layout changed :-)

**Comment by belohoub** [comment]
Reported to be OK on Telegram.
