### ISSUE TITLE
Remote view does not refresh properly

### ISSUE THREAD

**Issue by kugiigi** [belohoub/UBsync#22]
### Steps to Reproduce
1. Go to accounts list
2. Select an account
3. Add a new target
4. Select local directory
5. Select remote directory

### Expected Results
Shows the list of root folders of the remote server

### Actual Results
No list shown. Only the text on how to add a target is shown.

### Additional Information
This issue does not happen when editing the target again from the main page.
Also, the issue stopped happening though not sure what exactly triggered it. Last I remember is I tried to select the remote directory first before the local. After that, it worked fine until I restarted the app

**Comment by belohoub** [comment]
Thank you for reporting!

This is related to issue #16

**Comment by belohoub** [comment]
This will be fixed as in issue #16
