### ISSUE TITLE
Target list cannot be scrolled properly

### ISSUE THREAD

**Issue by kugiigi** [belohoub/UBsync#23]
### Steps to Reproduce
1. Add targets that will make the list longer than the phone's height, in short make the list scrollable

### Expected Results
List is scrollable as expected

### Actual Results
List is scrollable but when you scroll further down, the list seems to reset to the top making it impossible to select the bottom items.

**Comment by belohoub** [comment]
Thank you for reporting.

It looks like an regression. This will be solved together with issue #2

**Comment by belohoub** [comment]
Could you confirm this issue for the new OTA? I do not experience this issue after the last OTA upgrade.

**Comment by belohoub** [comment]
This issue is not observed anymore.
