### ISSUE TITLE
Bug: target list jumps back to top after scrolling down

### ISSUE THREAD

**Issue by luksus42** [belohoub/UBsync#27]
This issue exists in the xenial and the focal version.

I have configured 13 targets.
As soon as the third target is "leaving" the top of the display, when scrolling down, and the finger is released, the list jumps back and displays the third target at the top.

That makes it very hard, to edit the targets in the bottom of the list. You have to be very quick in tapping it, before it jumps back to top.

https://user-images.githubusercontent.com/6659488/229385094-decbd5df-248b-433a-947c-9f32d2cc6ca8.mp4

**Comment by belohoub** [comment]
@luksus42 Thank you for reporting.

Also the accounts page was affected.

I fixed it in the Focal branch, and I also added some descriptive text when "pulling the page down" to tell users, that the list will be updated when finger/mouse is released.

I currently do not plan to fix it for Xenial - if you think it is a severe issue, I'll fix it, but I think most users have one account and few targets, thus they will never notice... but it's just a guess :-) If you need it on Xenial, I'll backport it.

Please try the pre-release 0.7.6-RC2 and re-open if there is some regression or you think backporting to Xenial is important.

**Comment by luksus42** [comment]
It works, thanks.
I am ok with the focal-only fix.
