### ISSUE TITLE
Weblate integration

### ISSUE THREAD

**Issue by comradekingu** [belohoub/UBsync#31]
Currently it fails to sync https://hosted.weblate.org/projects/ubports/ubsync/#alerts
I think
https://docs.weblate.org/en/latest/admin/continuous.html#automatically-receiving-changes-from-github and possibly
adding the
https://github.com/weblate user to the org here helps.

**Comment by belohoub** [comment]
Yes, it was configured a day ago and it is not configured on my (github repo) side yet :-)

I'll add it as soon as possible, while it is now on my to-do list.

**Comment by belohoub** [comment]
@comradekingu Weblate is now integrated and we use pull requests :-)
